Add custom domain suffix option (base_domain)
ansible-collections/google.cloud pull request #522
Opened 2022-11-25 07:54 UTC by cthu1hoo

##### SUMMARY
While working with GCP inventory our team ran into a problem - inventory returns hostnames without FQDN which means we need to go through various hacks in our playbook inventories instead of using inventory_hostname as intended. This was particularly annoying when trying to configure multi-component deployments which refer to each other by inventory hostnames which need to be FQDN.

I've added a simple option (does nothing by default) that appends a custom domain suffix to all returned hosts which is sufficient for our needs as we use single base domain suffix per environment.

Having this really simplified dealing with GCP inventory and, being entirely optional and disabled by default, shouldn't have any side-effects. Would really appreciate this being reviewed and merged. Thanks in advance.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
- GCP Inventory

##### ADDITIONAL INFORMATION

2022-11-27 06:39 UTC, toumorokoshi requested changes
Thanks for the contribution! The feature sounds good to add, added a few comments that would be good to address first.

2022-11-27 06:39 UTC, toumorokoshi commented on plugins/inventory/gcp_compute.py
> +          description: Custom domain suffix to append to all hosts.
```suggestion
          description: Custom domain suffix. If set, this string will be appended to all hosts.
```

2022-11-27 06:39 UTC, toumorokoshi commented on plugins/inventory/gcp_compute.py
> +        if self.get_option("base_domain"):
please remove this if. Otherwise the `base_domain` variable will not be found if it is not a set option, and crash on line 437.

2022-11-27 06:39 UTC, toumorokoshi commented on plugins/inventory/gcp_compute.py
> +        base_domain:
for the argument name: can it just be called "name_suffix"? It's going to be appended to the name of all hosts, so it' s not specific to domains.

2022-11-27 07:00 UTC, cthu1hoo commented
@toumorokoshi thanks for your feedback, it all sounds reasonable to me. I've renamed the option to `name_suffix` and made other changes according to your comments. 👍

2022-11-27 07:00 UTC, cthu1hoo commented on plugins/inventory/gcp_compute.py
> +          description: Custom domain suffix to append to all hosts.
done.

2022-11-29 05:58 UTC, toumorokoshi approved these changes
LGTM, thanks!

2022-11-29 05:59 UTC, merged